services:
  user-db:
    image: postgres:16-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  menu-db:
    image: postgres:16-alpine
    container_name: menu-db
    environment:
      POSTGRES_DB: menudb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - menu-db-data:/var/lib/postgresql/data

  order-db:
    image: postgres:16-alpine
    container_name: order-db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    depends_on:
      - user-db
    ports:
      - "8081:8081"
    environment:
      DB_HOST: user-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: S3cr3tK3yF0rJWTAuthThatIsAtLeast256BitsL0ng!!Change-In-Prod

  menu-service:
    build:
      context: .
      dockerfile: menu-service/Dockerfile
    container_name: menu-service
    depends_on:
      - menu-db
    ports:
      - "8082:8082"
    environment:
      DB_HOST: menu-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: S3cr3tK3yF0rJWTAuthThatIsAtLeast256BitsL0ng!!Change-In-Prod

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    depends_on:
      - order-db
      - menu-service
    ports:
      - "8083:8083"
    environment:
      DB_HOST: order-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: S3cr3tK3yF0rJWTAuthThatIsAtLeast256BitsL0ng!!Change-In-Prod
      MENU_SERVICE_HOST: menu-service

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - user-service
      - menu-service
      - order-service
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: 8081
      MENU_SERVICE_HOST: menu-service
      MENU_SERVICE_PORT: 8082
      ORDER_SERVICE_HOST: order-service
      ORDER_SERVICE_PORT: 8083

volumes:
  user-db-data:
  menu-db-data:
  order-db-data: