server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8081}
          predicates:
            - Path=/users/**

        - id: menu-service
          uri: http://${MENU_SERVICE_HOST:localhost}:${MENU_SERVICE_PORT:8082}
          predicates:
            - Path=/menu/**

        - id: order-service
          uri: http://${ORDER_SERVICE_HOST:localhost}:${ORDER_SERVICE_PORT:8083}
          predicates:
            - Path=/orders/**