apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: foodordering-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              value: order-db
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: JWT_SECRET
              value: S3cr3tK3yF0rJWTAuthThatIsAtLeast256BitsL0ng!!Change-In-Prod
            - name: MENU_SERVICE_HOST
              value: menu-service